spring.datasource.url=jdbc:mysql://localhost:3306/trip_split
spring.datasource.username=${TRIP_SPLIT_DB_USERNAME}
spring.datasource.password=${TRIP_SPLIT_DB_PASSWORD}

amazonProperties.region=us-east-1
amazonProperties.endpointUrl=https://s3.amazonaws.com
amazonProperties.accessKey=${YOUR_ACCESS_KEY}
amazonProperties.secretKey=${YOUR_SECRET_KEY}
amazonProperties.bucketName=trip-split

logging.level.com.amazonaws.request=DEBUG
logging.level.com.amazonaws.auth=DEBUG
logging.level.learn.tripsplit=DEBUG
