@url = http://localhost:8080/api/user

### Token (This is unique to everyone)

@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0cmlwLXNwbGl0Iiwic3ViIjoidGVzdEV4YW1wbGUiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTc1MzQ1NzA4Nn0.lCLsNTg4lvnKghjmUBB5a4PcJb1QykSXcbJ2rkVa1Fk

### findAll()

GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

### findById()

GET {{url}}/2 HTTP/1.1
Authorization: Bearer {{token}}

### update()

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "appUserId": 2,
    "firstName": "Claudian",
    "lastName": "O'Lynn",
    "email": "claudian.olynn@example.com",
    "username": "claudiano",
    "passwordHash": "hash_1_example"
}

### deleteById()

DELETE {{url}}/5 HTTP/1.1
Authorization: Bearer {{token}}
