@url = http://localhost:8080/api/groups

### Token (This is unique to everyone)
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0cmlwLXNwbGl0Iiwic3ViIjoidGVzdEV4YW1wbGUiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTc1MzQ1NzA4Nn0.lCLsNTg4lvnKghjmUBB5a4PcJb1QykSXcbJ2rkVa1Fk

### findAll()

GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

### findById()

GET {{url}}/2 HTTP/1.1
Authorization: Bearer {{token}}

### add()

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Added Group",
  "description": "Added Group",
  "members": [
    {
      "email": "alice.johnson@example.com"
    },
    {
      "email": "bob.smith@example.com"
    }
  ]
}

### update() - updates only group fields, not users List

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "groupId": 2,
  "name": "Updated Group",
  "description": "This group has been updated",
  "createdBy": 6,
  "users": [
    {
      "userId": 0,
      "groupId": 0,
      "isAdmin": true,
      "user": {
        "appUserId": 6
      }
    }
  ]
}

### deleteById()

DELETE {{url}}/5 HTTP/1.1
Authorization: Bearer {{token}}