@url = http://localhost:8080/api/group

### Token (This is unique to everyone)
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0cmlwLXNwbGl0Iiwic3ViIjoiYWxpY2VtIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE3NTMzMTgyNjV9.-e1xBQGqGUMq-bhlRbEQCxwNe41pRX12FiyIf-3qLWU

### findAll()

GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

### findById()

GET {{url}}/2 HTTP/1.1
Authorization: Bearer {{token}}

### add()

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Added Group",
  "description": "Added Group",
  "createdBy": {
    "appUserId": 2,
    "firstName": "Bob",
    "lastName": "Smith",
    "email": "bob.smith@example.com",
    "username": "bobsmith",
    "passwordHash": "hash_2_example",
    "disabled": false,
    "groups": [],
    "expenses": [],
    "roles": ["User"]
  },
  "users": [
    {
      "groupId": 0,
      "isAdmin": true,
      "user": {
        "appUserId": 2,
        "firstName": "Bob",
        "lastName": "Smith",
        "email": "bob.smith@example.com",
        "username": "bobsmith",
        "passwordHash": "hash_2_example",
        "disabled": false,
        "groups": [],
        "expenses": [],
        "roles": ["User"]
      }
    }
  ]
}

### update()

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "groupId": 2,
  "name": "Updated Group",
  "description": "Updated Group",
  "createdBy": {
    "appUserId": 2,
    "firstName": "Bob",
    "lastName": "Smith",
    "email": "bob.smith@example.com",
    "username": "bobsmith",
    "passwordHash": "hash_2_example",
    "disabled": false,
    "groups": [],
    "expenses": [],
    "roles": ["User"]
  },
  "users": [
    {
      "userId": 2,
      "groupId": 2,
      "isAdmin": true,
      "user": {
        "appUserId": 2,
        "firstName": "Bob",
        "lastName": "Smith",
        "email": "bob.smith@example.com",
        "username": "bobsmith",
        "passwordHash": "hash_2_example",
        "disabled": false,
        "groups": [],
        "expenses": [],
        "roles": ["User"]
      }
    }
  ]
}

### deleteById()

DELETE {{url}}/5 HTTP/1.1
Authorization: Bearer {{token}}