@url = http://localhost:8080/api/auth

### Authenticate

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "bob@jones.com",
    "password": "P@ssw0rd!"
}

### Register

POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bob",
    "lastName": "Jones",
    "email": "bob@jones.com",
    "username": "bobj",
    "password": "P@ssw0rd!"
}

###


